/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restapisb;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

  /*
   * @EnableWebSecurity
   * 
   * @Configuration
   * class WebSecurityConfig extends WebSecurityConfigurerAdapter {
   * 
   * @Override
   * protected void configure(HttpSecurity http) throws Exception {
   * http.csrf()
   * .disable()
   * .addFilterAfter(new JWTAuthorizationFilter(), UsernamePasswordAuthenticationFilter.class)
   * .authorizeRequests()
   * .antMatchers(HttpMethod.POST, "/user")
   * .permitAll()
   * .antMatchers(HttpMethod.POST, "/user/login")
   * .permitAll()
   * .anyRequest()
   * .authenticated();
   * }
   * }
   * 
   */
}
